const fs = require("fs");

function getMonospacedFont() {
    const paths = [
        "C:\\Windows\\Fonts\\consola.ttf", // Consolas
        "C:\\Windows\\Fonts\\cour.ttf",    // Courier New
        "C:\\Windows\\Fonts\\lucon.ttf",   // Lucida Console
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/freefont/FreeMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/System/Library/Fonts/Supplemental/Courier New.ttf",
        "/Library/Fonts/Courier New.ttf"
    ];

    for (const p of paths) {
        if (fs.existsSync(p)) {
            return p;
        }
    }
    return "Courier"; // fallback
}

function drawTitle(doc) {
    const pageWidth = doc.page.width;
    doc
        .rect(0, 0, pageWidth, 80)
        .fill("#1E40AF");

    doc
        .fillColor("white")
        .fontSize(24)
        .font("Helvetica-Bold")
        .text("CodeScope AI", 50, 20);

    doc
        .fontSize(12)
        .font("Helvetica-Oblique")
        .text("AI Project Review Report", 50, 52);

    doc.fillColor("black").font("Helvetica");
}

function drawProjectInfo(doc, project) {
    doc.y = 110;

    doc
        .font("Helvetica-Bold")
        .fontSize(22)
        .fillColor("#1F2937")
        .text(project.title);

    doc.moveDown(0.5);

    doc
        .font("Helvetica")
        .fontSize(11)
        .fillColor("#4B5563")
        .text(`Status: ${project.reviewStatus}`);

    doc.text(
        `Generated: ${project.reviewedAt ? new Date(project.reviewedAt).toLocaleString() : new Date().toLocaleString()}`
    );

    doc.moveDown(0.8);

    const currentY = doc.y;
    doc
        .moveTo(50, currentY)
        .lineTo(doc.page.width - 50, currentY)
        .strokeColor("#E5E7EB")
        .lineWidth(1)
        .stroke();

    doc.moveDown(1);
    doc.fillColor("black");
}

function drawHeading(doc, text) {
    doc.moveDown(1.2);

    if (doc.y > doc.page.height - 100) {
        doc.addPage();
    }

    doc
        .font("Helvetica-Bold")
        .fillColor("#1E40AF")
        .fontSize(15)
        .text(text);

    doc.fillColor("black").font("Helvetica");
    doc.moveDown(0.5);
}

function drawParagraph(doc, text) {
    const parts = text.split("```");
    for (let i = 0; i < parts.length; i++) {
        if (i % 2 === 1) {
            // Code block: render in monospaced font
            const codeContent = parts[i].replace(/^[a-z]*\n/i, "");
            doc.font(getMonospacedFont()).fontSize(9.5).fillColor("#374151");
            doc.moveDown(0.5);
            doc.text(codeContent, {
                width: 480,
                align: "left",
                lineGap: 2,
                indent: 10
            });
            doc.fillColor("black").font("Helvetica");
            doc.moveDown(0.5);
        } else {
            // Regular text
            if (parts[i].trim().length > 0) {
                doc.font("Helvetica").fontSize(12);
                doc.text(parts[i].trim(), {
                    width: 500,
                    align: "left",
                    lineGap: 5
                });
            }
        }
    }
}

function drawFooter(doc) {

    doc.moveDown(2);

    doc
        .fillColor("gray")
        .fontSize(10)
        .text(
            "Generated by CodeScope AI",
            {
                align: "center"
            }
        );

}

module.exports = {

    drawTitle,
    drawProjectInfo,
    drawHeading,
    drawParagraph,
    drawFooter,
    getMonospacedFont

};